const zones = [
  { key: 1, value: 'Abasto', label: 'Abasto' },
  { key: 2, value: 'Agronomía', label: 'Agronomía' },
  { key: 3, value: 'Almagro', label: 'Almagro' },
  { key: 4, value: 'Balvanera', label: 'Balvanera' },
  { key: 5, value: 'Barracas', label: 'Barracas' },
  { key: 6, value: 'Belgrano', label: 'Belgrano' },
  { key: 7, value: 'Boedo', label: 'Boedo' },
  { key: 8, value: 'Caballito', label: 'Caballito' },
  { key: 9, value: 'Centro', label: 'Centro' },
  { key: 10, value: 'Chacarita', label: 'Chacarita' },
  { key: 11, value: 'Coghlan', label: 'Coghlan' },
  { key: 12, value: 'Colegiales', label: 'Colegiales' },
  { key: 13, value: 'Constitución', label: 'Constitución' },
  { key: 14, value: 'Devoto', label: 'Devoto' },
  { key: 15, value: 'Flores', label: 'Flores' },
  { key: 16, value: 'Floresta', label: 'Floresta' },
  { key: 17, value: 'La Boca', label: 'La Boca' },
  { key: 18, value: 'La Paternal', label: 'La Paternal' },
  { key: 19, value: 'Liniers', label: 'Liniers' },
  { key: 20, value: 'Mataderos', label: 'Mataderos' },
  { key: 21, value: 'Monte Castro', label: 'Monte Castro' },
  { key: 22, value: 'Morón', label: 'Morón' },
  { key: 23, value: 'Montserrat', label: 'Montserrat' },
  { key: 24, value: 'Nueva Pompeya', label: 'Nueva Pompeya' },
  { key: 25, value: 'Núñez', label: 'Núñez' },
  { key: 26, value: 'Otro', label: 'Otro' },
  { key: 27, value: 'Palermo', label: 'Palermo' },
  { key: 28, value: 'Parque Avellaneda', label: 'Parque Avellaneda' },
  { key: 29, value: 'Parque Chacabuco', label: 'Parque Chacabuco' },
  { key: 30, value: 'Parque Chas', label: 'Parque Chas' },
  { key: 31, value: 'Parque Patricios', label: 'Parque Patricios' },
  { key: 32, value: 'Paternal', label: 'Paternal' },
  { key: 33, value: 'Puerto Madero', label: 'Puerto Madero' },
  { key: 34, value: 'Recoleta', label: 'Recoleta' },
  { key: 35, value: 'Retiro', label: 'Retiro' },
  { key: 36, value: 'Saavedra', label: 'Saavedra' },
  { key: 37, value: 'San Cristóbal', label: 'San Cristóbal' },
  { key: 38, value: 'San Nicolás', label: 'San Nicolás' },
  { key: 39, value: 'San Telmo', label: 'San Telmo' },
  { key: 40, value: 'Versalles', label: 'Versalles' },
  { key: 41, value: 'Villa Crespo', label: 'Villa Crespo' },
  { key: 42, value: 'Villa Devoto', label: 'Villa Devoto' },
  { key: 43, value: 'Villa General Mitre', label: 'Villa General Mitre' },
  { key: 44, value: 'Villa Lugano', label: 'Villa Lugano' },
  { key: 45, value: 'Villa Luro', label: 'Villa Luro' },
  { key: 46, value: 'Villa Ortúzar', label: 'Villa Ortúzar' },
  { key: 47, value: 'Villa Pueyrredón', label: 'Villa Pueyrredón' },
  { key: 48, value: 'Villa Real', label: 'Villa Real' },
  { key: 49, value: 'Villa Riachuelo', label: 'Villa Riachuelo' },
  { key: 50, value: 'Villa Santa Rita', label: 'Villa Santa Rita' },
  { key: 51, value: 'Villa Soldati', label: 'Villa Soldati' },
  { key: 52, value: 'Villa Urquiza', label: 'Villa Urquiza' },
  { key: 53, value: 'Villa del Parque', label: 'Villa del Parque' },
  { key: 54, value: 'Vélez Sarsfield', label: 'Vélez Sarsfield' }
];


export default zones;