const users = [
    {
      id: 1,
      generator: "Tony Reichert",
      creation_date: "2024-01-10",
      recolection_date: "2024-01-12",
      waste_type: "Plástico",
      size: 3,
      zone: "Palermo",
      status: "Completada",
    },
    {
      id: 2,
      generator: "Zoey Lang",
      creation_date: "2024-01-11",
      recolection_date: "2024-01-13",
      waste_type: "Papel",
      size: 2,
      zone: "Recoleta",
      status: "Cancelada",
    },
    {
      id: 3,
      generator: "Jane Fisher",
      creation_date: "2024-01-12",
      recolection_date: "2024-01-14",
      waste_type: "Vidrio",
      size: 1,
      zone: "Belgrano",
      status: "Completada",
    },
    {
      id: 4,
      generator: "William Howard",
      creation_date: "2024-01-13",
      recolection_date: "2024-01-15",
      waste_type: "Metales",
      size: 4,
      zone: "Villa Urquiza",
      status: "Coordinada",
    },
    {
      id: 5,
      generator: "Kristen Copper",
      creation_date: "2024-01-14",
      recolection_date: "2024-01-16",
      waste_type: "Orgánico",
      size: 2,
      zone: "Flores",
      status: "Completada",
    },
    {
      id: 6,
      generator: "Brian Kim",
      creation_date: "2024-01-15",
      recolection_date: "2024-01-17",
      waste_type: "Electrónicos",
      size: 5,
      zone: "Caballito",
      status: "Completada",
    },
    {
      id: 7,
      generator: "Michael Hunt",
      creation_date: "2024-01-16",
      recolection_date: "2024-01-18",
      waste_type: "Plástico",
      size: 2,
      zone: "San Cristóbal",
      status: "Cancelada",
    },
    {
      id: 8,
      generator: "Samantha Brooks",
      creation_date: "2024-01-17",
      recolection_date: "2024-01-19",
      waste_type: "Papel",
      size: 3,
      zone: "Nuñez",
      status: "Completada",
    },
    {
      id: 9,
      generator: "Frank Harrison",
      creation_date: "2024-01-18",
      recolection_date: "2024-01-20",
      waste_type: "Vidrio",
      size: 2,
      zone: "Almagro",
      status: "Coordinada",
    },
    {
      id: 10,
      generator: "Emma Adams",
      creation_date: "2024-01-19",
      recolection_date: "2024-01-21",
      waste_type: "Metales",
      size: 1,
      zone: "Barracas",
      status: "Completada",
    },
    {
      id: 11,
      generator: "Brandon Stevens",
      creation_date: "2024-01-20",
      recolection_date: "2024-01-22",
      waste_type: "Orgánico",
      size: 4,
      zone: "Villa del Parque",
      status: "Completada",
    },
    {
      id: 12,
      generator: "Megan Richards",
      creation_date: "2024-01-21",
      recolection_date: "2024-01-23",
      waste_type: "Electrónicos",
      size: 3,
      zone: "Villa Devoto",
      status: "Cancelada",
    },
    {
      id: 13,
      generator: "Oliver Scott",
      creation_date: "2024-01-22",
      recolection_date: "2024-01-24",
      waste_type: "Plástico",
      size: 1,
      zone: "Flores",
      status: "Completada",
    },
    {
      id: 14,
      generator: "Grace Allen",
      creation_date: "2024-01-23",
      recolection_date: "2024-01-25",
      waste_type: "Papel",
      size: 5,
      zone: "Monte Castro",
      status: "Completada",
    },
    {
      id: 15,
      generator: "Noah Carter",
      creation_date: "2024-01-24",
      recolection_date: "2024-01-26",
      waste_type: "Vidrio",
      size: 3,
      zone: "Villa Luro",
      status: "Cancelada",
    },
    {
      id: 16,
      generator: "Ava Perez",
      creation_date: "2024-01-25",
      recolection_date: "2024-01-27",
      waste_type: "Metales",
      size: 2,
      zone: "Colegiales",
      status: "Completada",
    },
    {
      id: 17,
      generator: "Liam Johnson",
      creation_date: "2024-01-26",
      recolection_date: "2024-01-28",
      waste_type: "Orgánico",
      size: 4,
      zone: "Palermo",
      status: "Completada",
    },
    {
      id: 18,
      generator: "Sophia Taylor",
      creation_date: "2024-01-27",
      recolection_date: "2024-01-29",
      waste_type: "Electrónicos",
      size: 3,
      zone: "Caballito",
      status: "Completada",
    },
    {
      id: 19,
      generator: "Lucas Harris",
      creation_date: "2024-01-28",
      recolection_date: "2024-01-30",
      waste_type: "Plástico",
      size: 2,
      zone: "San Cristóbal",
      status: "Cancelada",
    },
    {
      id: 20,
      generator: "Mia Robinson",
      creation_date: "2024-01-29",
      recolection_date: "2024-01-31",
      waste_type: "Papel",
      size: 5,
      zone: "Nuñez",
      status: "Ingresada",
    },
  ];  

export {users};

